### PR TITLE
Category Controller and Model

### LINKED ISSUE #31: Category Controller and Models file
Code Files for implementing  Category Controller

### PR DESCRIPTION
**Pull request by Himanshuu-Gupta**
Category Controller and Model code files

### CODE REVIEW

**Comment by ShreyanshPrajapati** [comment]
Please remove init function instead of keeping it blank for consistency.

**Comment by ShreyanshPrajapati** [comment]
LGTM.

**Comment by Himanshuu-Gupta** [comment]
@ShreyanshPrajapati  Init function removed as suggested

**Comment by ShreyanshPrajapati** [comment]
@Himanshuu-Gupta  Thanks, please merge the PR

**Pull request merged**
